# -*- coding: utf-8 -*-
"""happy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMdnBXKqWxeNJhMt_4yhagXPdyay4Sz3
"""

from google.colab import drive
drive.mount('/content/drive')

!nvidia-smi

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import cv2
import os

img = image.load_img("/content/drive/MyDrive/colab_notebook/happysad/OPEN CV/Training/Happy/WhatsApp Image 2025-10-09 at 3.22.00 PM.jpeg")

plt.imshow(img)

i1 = cv2.imread("/content/drive/MyDrive/colab_notebook/happysad/OPEN CV/Training/Happy/WhatsApp Image 2025-10-09 at 3.22.00 PM.jpeg")
i1

i1.shape

train = ImageDataGenerator(rescale = 1/200)
validation = ImageDataGenerator(rescale = 1/200)

train_dataset = train.flow_from_directory("/content/drive/MyDrive/colab_notebook/happysad/OPEN CV/Training",
                                          target_size = (200, 200),
                                          batch_size = 32,
                                          class_mode = 'binary')
validation_dataset = train.flow_from_directory("/content/drive/MyDrive/colab_notebook/happysad/OPEN CV/Validation",
                                               target_size = (200, 200),
                                          batch_size = 32,
                                          class_mode = 'binary')

train_dataset.class_indices

train_dataset.classes

model = tf.keras.models.Sequential([tf.keras.layers.Conv2D(16,(3,3),activation = 'relu',input_shape = (200,200,3)),
                                    tf.keras.layers.MaxPool2D(2,2),

                                    tf.keras.layers.Conv2D(32,(3,3),activation = 'relu'),
                                    tf.keras.layers.MaxPool2D(2,2),

                                    tf.keras.layers.Conv2D(64,(3,3),activation = 'relu'),
                                    tf.keras.layers.MaxPool2D(2,2),

                                    tf.keras.layers.Flatten(),

                                    tf.keras.layers.Dense(512,activation = 'relu'),
                                    tf.keras.layers.Dense(1,activation = 'sigmoid')



                                     ])

model.compile(loss = 'binary_crossentropy',
               optimizer = tf.keras.optimizers.RMSprop(learning_rate = 0.001),
               metrics = ['accuracy']
                )

model_fit = model.fit(train_dataset,epochs = 15)

dir_path = '/content/drive/MyDrive/colab_notebook/happysad/OPEN CV/Testing'
for i in os.listdir(dir_path):
  print(i)
  # img = image.load_img(dir_path+'//'+i,target_size = (200,200))
  # plt.imshow(img)
  # plt.show()

dir_path = '/content/drive/MyDrive/colab_notebook/happysad/OPEN CV/Testing'
for i in os.listdir(dir_path):
  img = image.load_img(dir_path+'//'+i,target_size = (200,200))
  plt.imshow(img)
  plt.show()

for i in os.listdir(dir_path):
  img = image.load_img(dir_path+ '//' +i , target_size = (200,200))
  plt.imshow(img)
  plt.show()

  x = image.img_to_array(img)
  x = np.expand_dims(x, axis = 0)
  images = np.vstack([x])

  val = model.predict(images)
  if val == 0:
    print("I am Happy")
  else:
    print("I am Unhappy")